### ISSUE TITLE
Tsview

### ISSUE THREAD

**Issue by NKakar** [insarlab/MintPy#977]
**Description of the problem**

I am not able to plot the Tsview in version 1.5.1 and it works fine in version 1.3.3 and 1.3.2! 
TypeError: timeseriesViewer.configure() missing 1 required positional argument: 'inps'

**Full script that generated the error**

```
PASTE CODE HERE
```
%matplotlib notebook

import os
import matplotlib.pyplot as plt
from mintpy.tsview import timeseriesViewer

# visualization functions
def tsview(fname, yx=None, figsize_img=[5, 4], figsize_pts=[5, 2]):
    """Plot input file using tsview.py"""
    cmd = 'tsview.py {} --ms 4 --noverbose --sub-lat 3690000.0 3705957.0 --sub-lon 450000.0 475428.0'.format(fname)
    if yx is not None:
        cmd += ' --yx {} {}'.format(yx[0], yx[1])
    obj = timeseriesViewer(cmd)
    obj.configure()
    obj.figsize_img = figsize_img
    obj.figsize_pts = figsize_pts
    obj.plot()
    return obj

ts_file = os.path.expanduser('/DESCENDING/D_P_78_F_/3N/timeseries_ERA5_demErr.h5')
tsview(ts_file, yx=(1273,2271), figsize_img=[8,6])

**Full error message**

---> 21 tsview(ts_file, yx=(1273,2271), figsize_img=[8,6])

Cell In[1], line 14, in tsview(fname, yx, figsize_img, figsize_pts)
     12     cmd += ' --yx {} {}'.format(yx[0], yx[1])
     13 obj = timeseriesViewer(cmd)
---> 14 obj.configure()
     15 obj.figsize_img = figsize_img
     16 obj.figsize_pts = figsize_pts

TypeError: timeseriesViewer.configure() missing 1 required positional argument: 'inps'

PASTE ERROR MESSAGE HERE
```


**System information**

* Operating system: <!-- macOS, Linux, Windows, etc. -->
* Python environment: <!-- conda, macports, pip, path setup, etc. -->
* MintPy version: <!-- output of `smallbaselineApp.py -v` -->
* Your custom / default template file (if the bug is related to a specific dataset): <!-- It helps the diagnose a lot if you could post the configurations you used. You can drag-and-drop them here directly. -->

**Comment by yunjunz** [comment]
You are right, the old example is broken in mintpy v1.5.1.

The `%matplotlib notebook` is not very convenient anymore, and has been switched to `%matplotlib widget` for interactive plotting in notebooks. The following should be easier to use:

```python
%matplotlib widget
import os
from mintpy.cli import tsview
ts_file = os.path.expanduser('~/data/test/FernandinaSenDT128/mintpy/timeseries_SET_ERA5_ramp_demErr.h5')
cmd = f'{ts_file} --yx 273 271 '
tsview.main(cmd.split())
```

Let's keep this issue open until I fixed the example comment and notebook.
